# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe -flto=auto -fuse-linker-plugin"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

USE="-debug -doc -introspection -vala -bluetooth -wifi -wext -cups -fortran -nls -clamav -cdr -dvd -dvdr -dvb -tiff -webp -joystick -lame -libnotify -mp3 -mtp -nntp -policykit -qt5 -qt6 -speech -telemetry -upnp -upnp-av -vcd -vnc -wayland -xemacs -ios -imap -ibm -zeroconf -sendmail -accessibility -kwallet -gnome-keyring -pulseaudio -gnome -kde -plasma -xfce -ssh-agent -png -drm \ 
lto jit dist-kernel X alsa sound-server pulseaudio xinerama \
nvenc vdpau nvidia"

VIDEO_CARDS="nvidia"
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3"
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

EMERGE_DEFAULT_OPTS="--quiet"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
